import type { Metadata } from 'next';
import './globals.scss';
import Header from '@/components/Organisms/Header';
import Footer from '@/components/Organisms/Footer';

export const metadata: Metadata = {
  title: 'Happy Coaching',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
